version: "3.7"
services:
  haystack-api:
    container_name: chatbox-nlp-api-gunicorn-container
    image: public.ecr.aws/q0s5b2t6/chatbox-nlp-api:latest
    ports:
      - 8080:8080
    # build:
    #   context: .
