version: 1.11.0

components:
  - name: MyESQNARetriever
    type: EmbeddingRetriever
    params:
      document_store: MyQNADocumentStore
      embedding_model: sentence-transformers/all-MiniLM-L6-v2
      scale_score: false
      top_k: 5

  - name: SparseRetriever
    type: BM25Retriever
    params:
      document_store: DocumentStore
      top_k: 10

  - name: JoinAns
    type: JoinAnswers
    params:
      join_mode: concatenate
      sort_by_score: true
      top_k_join: 1

  - name: MyReader
    type: FARMReader
    params:
      model_name_or_path: deepset/roberta-base-squad2
      top_k: 5

  - name: QNADocsToAnswers
    type: Docs2Answers

  - name: DocumentStore
    type: ElasticsearchDocumentStore
    params:
      host: 391f53d8501748afaf1fbfc591ed43e1.us-central1.gcp.cloud.es.io
      username: elastic
      password: VjLfWuuVTOnUZbFlI6a9eriq
      port: 9243
      scheme: https
      index: document

  - name: MyQNADocumentStore
    type: ElasticsearchDocumentStore
    params:
      host: 391f53d8501748afaf1fbfc591ed43e1.us-central1.gcp.cloud.es.io
      username: elastic
      password: VjLfWuuVTOnUZbFlI6a9eriq
      port: 9243
      scheme: https
      index: qna_document
      embedding_field: question_emb
      embedding_dim: 384
      excluded_meta_data:
        - question_emb
      similarity: cosine

pipelines:
  - name: search_pipeline
    nodes:
      - name: SparseRetriever
        inputs: 
         - Query
      - name: MyESQNARetriever
        inputs: 
         - Query
      - name: MyReader
        inputs: 
         - SparseRetriever
      - name: QNADocsToAnswers
        inputs: 
         - MyESQNARetriever
      - name: JoinAns
        inputs: 
         - QNADocsToAnswers
         - MyReader
